<?php

/**
 * Phase 12 content library — industries. Each entry describes the industry's own technology
 * problems and maps them to Markedge capabilities; no two share paragraphs. Entries marked
 * 'priority' => false receive concise copy and stay in draft for later expansion.
 */
return [
    'healthcare' => [
        'priority' => true,
        'tagline' => 'Technology for clinics, hospitals and healthcare providers that must be reliable and private.',
        'short_description' => 'Patient-facing portals, operational applications, secured infrastructure and tested backups for healthcare organisations.',
        'description' => '<p>Healthcare providers run on systems that cannot fail and data that cannot leak: appointment scheduling, patient records, lab and imaging workflows, billing and reporting. Downtime interrupts care; a data incident damages trust and can breach regulation.</p><p>Markedge works with healthcare organisations on patient-facing web and mobile touchpoints, internal applications that replace paper and spreadsheets, integrations between clinical and administrative systems, and the infrastructure discipline that keeps everything available, patched, backed up and access-controlled.</p>',
        'challenges' => [
            ['title' => 'Availability', 'text' => 'Clinical and scheduling systems must be monitored, maintained and recoverable.'],
            ['title' => 'Data protection', 'text' => 'Access control, encryption, logging and tested backups for patient data.'],
            ['title' => 'Fragmented systems', 'text' => 'Clinical, laboratory, billing and administrative tools that do not share data.'],
            ['title' => 'Patient experience', 'text' => 'Booking, results and communication that work on a phone.'],
        ],
        'faqs' => [['question' => 'Can you work within healthcare data regulations?', 'answer' => 'Data handling, storage location and access controls are agreed at the start of every engagement and documented; where formal compliance certification is required, we help evidence controls for the accredited auditor.']],
        'seo' => ['title' => 'Technology Services for Healthcare | Markedge Technologies', 'description' => 'Patient portals, operational applications, integrations, secured infrastructure and tested backups for clinics, hospitals and healthcare providers.'],
        'related' => ['services' => ['custom-business-applications', 'api-development', 'cybersecurity', 'backup-disaster-recovery', 'it-amc'], 'solutions' => ['it-infrastructure-modernisation', 'customer-experience'], 'products' => []],
    ],
    'manufacturing' => [
        'priority' => true,
        'tagline' => 'Connect the shop floor, the warehouse and the office.',
        'short_description' => 'Operational applications, integrations, plant networks and infrastructure management for manufacturers.',
        'description' => '<p>Manufacturers lose margin in the gaps between systems: production data on paper, inventory in a spreadsheet, orders in an accounting package, quality records in a filing cabinet. The plant network has to support machines, scanners and offices, and it has to stay up.</p><p>Markedge builds the applications and integrations that connect production, inventory, quality and finance; designs and maintains plant and office networks; and operates servers, backups and security so operations are not exposed to a single failure.</p>',
        'challenges' => [
            ['title' => 'Disconnected data', 'text' => 'Production, inventory, quality and finance recorded in separate places.'],
            ['title' => 'Plant connectivity', 'text' => 'Networks that must cover machines, scanners and offices reliably and securely.'],
            ['title' => 'Operational continuity', 'text' => 'Servers, backups and support that keep production systems available.'],
            ['title' => 'Traceability', 'text' => 'Records for quality, compliance and customer audits.'],
        ],
        'faqs' => [['question' => 'Do you integrate with existing ERP or accounting systems?', 'answer' => 'Integration is scoped per system; where an API or export exists we synchronise data, and where it does not we design the least manual handover possible.']],
        'seo' => ['title' => 'Technology Services for Manufacturing | Markedge Technologies', 'description' => 'Operational applications, ERP and inventory integrations, plant networks and infrastructure management for manufacturers.'],
        'related' => ['services' => ['custom-business-applications', 'api-development', 'networking', 'server-infrastructure-management', 'it-amc'], 'solutions' => ['business-automation', 'it-infrastructure-modernisation'], 'products' => []],
    ],
    'real-estate' => [
        'priority' => true,
        'tagline' => 'Generate, track and convert property enquiries.',
        'short_description' => 'Property websites, campaign landing pages, lead management and follow-up for developers, brokers and agencies.',
        'description' => '<p>Real estate is enquiry-driven: projects are marketed through search, social and portals, enquiries arrive in volume, and the businesses that respond fastest and follow up longest win. Enquiries lost in inboxes are lost sales.</p><p>Markedge builds property websites and campaign landing pages with lead capture and attribution, runs search and paid campaigns to defined cost-per-enquiry targets, and provides the Lead Management System so every enquiry is owned, followed up and reported by source.</p>',
        'challenges' => [
            ['title' => 'Enquiry volume without ownership', 'text' => 'Leads from portals, campaigns and calls with no single record.'],
            ['title' => 'Campaign accountability', 'text' => 'Knowing which campaigns and pages produce site visits and bookings.'],
            ['title' => 'Project marketing', 'text' => 'Landing pages and content for each project, built fast and measured.'],
            ['title' => 'Follow-up discipline', 'text' => 'Reminders, assignment and reporting across sales teams.'],
        ],
        'faqs' => [['question' => 'Can enquiries from property portals be brought into one system?', 'answer' => 'Where the portal offers e-mail or API delivery, enquiries can be captured into the Lead Management System with their source recorded.']],
        'seo' => ['title' => 'Technology & Lead Generation for Real Estate | Markedge Technologies', 'description' => 'Property websites, campaign landing pages, lead management and follow-up for developers, brokers and agencies.'],
        'related' => ['services' => ['web-development', 'performance-marketing', 'lead-generation', 'seo'], 'solutions' => ['sales-management', 'digital-growth'], 'products' => ['lead-management-system']],
    ],
    'education' => [
        'priority' => true,
        'tagline' => 'Admissions, campus IT and communication for schools, colleges and training providers.',
        'short_description' => 'Admissions lead management, institutional websites, campus networks and IT support for education providers.',
        'description' => '<p>Education providers market to prospective students, manage admissions across seasons, and run campuses where hundreds of people depend on the network and devices every day. Enquiry follow-up decides enrolment; campus IT decides whether teaching runs smoothly.</p><p>Markedge supports institutions with websites and campaigns that generate admissions enquiries, lead management for admissions teams, and campus networking, device management and IT support under an annual agreement.</p>',
        'challenges' => [
            ['title' => 'Admissions enquiries', 'text' => 'Seasonal enquiry volume that needs fast, tracked follow-up.'],
            ['title' => 'Campus connectivity', 'text' => 'Wireless coverage, segmentation and capacity for staff, students and guests.'],
            ['title' => 'Device and account management', 'text' => 'Onboarding, offboarding and support at scale.'],
            ['title' => 'Institutional website', 'text' => 'Programmes, admissions and events content managed by non-technical staff.'],
        ],
        'faqs' => [['question' => 'Can the admissions team use the Lead Management System?', 'answer' => 'Yes. Admissions enquiries are leads with a source, owner and follow-up; the system is demonstrated with an admissions scenario on request.']],
        'seo' => ['title' => 'Technology Services for Education | Markedge Technologies', 'description' => 'Admissions lead management, institutional websites, campus networks and IT support for schools, colleges and training providers.'],
        'related' => ['services' => ['web-development', 'lead-generation', 'networking', 'it-support', 'it-amc'], 'solutions' => ['sales-management', 'it-infrastructure-modernisation'], 'products' => ['lead-management-system']],
    ],
    'professional-services' => [
        'priority' => true,
        'tagline' => 'Technology for firms that sell expertise and depend on trust.',
        'short_description' => 'Client portals, internal workflow applications, secure IT and content-led marketing for consultancies, accountancies, legal and advisory firms.',
        'description' => '<p>Professional services firms run on knowledge, confidentiality and reputation. Clients expect secure handling of their information, responsive communication and evidence of expertise before they engage.</p><p>Markedge helps firms with client portals and document workflows, internal applications for engagement and approval tracking, secured and supported IT, and content marketing that demonstrates expertise to prospective clients.</p>',
        'challenges' => [
            ['title' => 'Confidential data', 'text' => 'Access control, encryption, backups and device security for client information.'],
            ['title' => 'Manual engagement tracking', 'text' => 'Proposals, approvals and time tracked in spreadsheets and e-mail.'],
            ['title' => 'Demonstrating expertise', 'text' => 'Content that answers client questions and earns enquiries.'],
            ['title' => 'Client communication', 'text' => 'Portals and secure document exchange instead of e-mail attachments.'],
        ],
        'faqs' => [['question' => 'How do you handle confidentiality during engagements?', 'answer' => 'Access, data handling and confidentiality terms are agreed before work starts, and Markedge staff operate with scoped, auditable access.']],
        'seo' => ['title' => 'Technology Services for Professional Services Firms | Markedge Technologies', 'description' => 'Client portals, workflow applications, secure IT and content-led marketing for consultancies, accountancies, legal and advisory firms.'],
        'related' => ['services' => ['custom-business-applications', 'cybersecurity', 'it-support', 'content-marketing', 'seo'], 'solutions' => ['business-automation', 'digital-growth'], 'products' => ['lead-management-system', 'recruitment-management-system']],
    ],
    'retail' => [
        'priority' => true,
        'tagline' => 'Connected stores, online presence and customer engagement.',
        'short_description' => 'E-commerce integrations, store networks, customer-facing apps and digital marketing for retailers.',
        'description' => '<p>Retail runs across stores, online channels and back-office systems that must share stock, orders and customer data. Store networks carry payments and inventory devices; websites and campaigns bring customers in; systems that do not talk to each other cost sales and time.</p><p>Markedge integrates e-commerce, point-of-sale and inventory systems, designs and maintains store networks, builds customer-facing web and mobile touchpoints, and runs digital marketing measured on enquiries and sales.</p>',
        'challenges' => [
            ['title' => 'Channel integration', 'text' => 'Stock, orders and customers consistent across store and online.'],
            ['title' => 'Store connectivity', 'text' => 'Reliable, segmented networks for payments, devices and guests.'],
            ['title' => 'Customer engagement', 'text' => 'Web, mobile and social touchpoints that convert.'],
            ['title' => 'Seasonal demand', 'text' => 'Campaigns and infrastructure that scale with peaks.'],
        ],
        'faqs' => [],
        'seo' => ['title' => 'Technology Services for Retail | Markedge Technologies', 'description' => 'E-commerce integrations, store networks, customer-facing apps and digital marketing for retailers.'],
        'related' => ['services' => ['api-development', 'networking', 'mobile-app-development', 'social-media-marketing', 'performance-marketing'], 'solutions' => ['customer-experience', 'digital-growth'], 'products' => []],
    ],
    'logistics' => [
        'priority' => true,
        'tagline' => 'Visibility across fleets, warehouses and customers.',
        'short_description' => 'Field and driver applications, tracking integrations and operational systems for logistics and distribution businesses.',
        'description' => '<p>Logistics depends on information moving as reliably as goods: where a shipment is, what a driver needs to do next, what the warehouse has received, what the customer has been told.</p><p>Markedge builds mobile applications for drivers and field staff with offline capture, integrates tracking, warehouse and customer systems, and builds customer-facing tracking and booking portals.</p>',
        'challenges' => [
            ['title' => 'Field data capture', 'text' => 'Proof of delivery, inspections and exceptions recorded on the move.'],
            ['title' => 'System integration', 'text' => 'Tracking, warehouse, order and customer systems exchanging data.'],
            ['title' => 'Customer visibility', 'text' => 'Portals and notifications for status and documents.'],
        ],
        'faqs' => [],
        'seo' => ['title' => 'Technology Services for Logistics | Markedge Technologies', 'description' => 'Driver and field applications, tracking and warehouse integrations, and customer portals for logistics and distribution businesses.'],
        'related' => ['services' => ['mobile-app-development', 'api-development', 'custom-business-applications'], 'solutions' => ['custom-software', 'business-automation'], 'products' => []],
    ],
    'recruitment' => [
        'priority' => true,
        'tagline' => 'Systems for agencies and hiring teams that place people.',
        'short_description' => 'Candidate and vacancy management, automation and client-facing tools for recruitment agencies and in-house hiring teams.',
        'description' => '<p>Recruitment businesses manage many vacancies, many candidates and many client relationships at once. Speed and organisation decide placements; lost feedback and slow scheduling lose candidates.</p><p>Markedge provides the Recruitment Management System, automation for screening and scheduling, integrations with job boards and communication tools where practical, and websites that attract candidates and clients.</p>',
        'challenges' => [
            ['title' => 'Candidate volume', 'text' => 'Screening, tracking and communication at scale.'],
            ['title' => 'Client coordination', 'text' => 'Feedback, interviews and offers across multiple clients.'],
            ['title' => 'Repetitive administration', 'text' => 'Scheduling, reminders and status updates done by hand.'],
        ],
        'faqs' => [],
        'seo' => ['title' => 'Technology for Recruitment Agencies | Markedge Technologies', 'description' => 'Recruitment management software, automation and candidate-facing websites for agencies and in-house hiring teams.'],
        'related' => ['services' => ['ai-automation', 'web-development', 'api-development'], 'solutions' => ['recruitment-automation'], 'products' => ['recruitment-management-system']],
    ],
    'bfsi' => [
        'priority' => false,
        'tagline' => 'Secure, auditable technology for banking, financial services and insurance.',
        'short_description' => 'Secure applications, integrations, infrastructure hardening and recovery planning for financial organisations.',
        'description' => '<p>Financial organisations need systems that are secure, auditable and recoverable. Markedge supports them with custom applications and integrations built with access control and audit trails, infrastructure security and tested disaster recovery.</p>',
        'challenges' => [['title' => 'Security and audit', 'text' => 'Access control, logging and evidence for every system.'], ['title' => 'Recoverability', 'text' => 'Tested backups and recovery objectives.']],
        'faqs' => [],
        'seo' => ['title' => 'Technology Services for BFSI | Markedge Technologies', 'description' => 'Secure applications, integrations, infrastructure hardening and recovery planning for banking, financial services and insurance organisations.'],
        'related' => ['services' => ['cybersecurity', 'backup-disaster-recovery', 'custom-business-applications'], 'solutions' => ['it-infrastructure-modernisation'], 'products' => []],
    ],
    'technology' => [
        'priority' => false,
        'tagline' => 'Engineering and operations capacity for technology companies.',
        'short_description' => 'Product engineering, cloud operations and design capacity for software and technology businesses.',
        'description' => '<p>Technology companies need engineering, design and operations capacity that can start quickly and work to their standards. Markedge provides product engineering, UI/UX and cloud operations as an extension of in-house teams.</p>',
        'challenges' => [['title' => 'Capacity', 'text' => 'Engineering and design that scales with the roadmap.'], ['title' => 'Operations', 'text' => 'Cloud, monitoring and backups run to a standard.']],
        'faqs' => [],
        'seo' => ['title' => 'Engineering Services for Technology Companies | Markedge Technologies', 'description' => 'Product engineering, UI/UX and cloud operations capacity for software and technology businesses.'],
        'related' => ['services' => ['product-development', 'ui-ux-design', 'cloud'], 'solutions' => ['product-development'], 'products' => []],
    ],
    'startups' => [
        'priority' => false,
        'tagline' => 'From MVP to a product and a business that can run.',
        'short_description' => 'Product discovery, MVP engineering, identity and growth foundations for early-stage companies.',
        'description' => '<p>Start-ups need to validate quickly without building foundations they will regret. Markedge helps with discovery, MVP engineering on scalable foundations, brand identity and the first growth channels.</p>',
        'challenges' => [['title' => 'Validate before over-building', 'text' => 'An MVP scoped to what must be proven.'], ['title' => 'Foundations', 'text' => 'Architecture, brand and measurement that survive growth.']],
        'faqs' => [],
        'seo' => ['title' => 'Technology & Growth Services for Startups | Markedge Technologies', 'description' => 'Product discovery, MVP engineering, brand identity and growth foundations for early-stage companies.'],
        'related' => ['services' => ['product-development', 'branding', 'digital-marketing'], 'solutions' => ['product-development', 'digital-growth'], 'products' => []],
    ],
    'smes' => [
        'priority' => false,
        'tagline' => 'One partner for the technology a growing business depends on.',
        'short_description' => 'Website, IT maintenance, security, lead generation and business applications for small and medium enterprises.',
        'description' => '<p>Small and medium businesses rarely have specialists for every technology need. Markedge acts as one accountable partner across website and marketing, IT maintenance and security, and the applications that replace spreadsheets.</p>',
        'challenges' => [['title' => 'No in-house IT', 'text' => 'Maintenance, support and security under one agreement.'], ['title' => 'Enquiries', 'text' => 'A website and channels that produce and track leads.']],
        'faqs' => [],
        'seo' => ['title' => 'Technology Services for SMEs | Markedge Technologies', 'description' => 'Website, IT maintenance, security, lead generation and business applications for small and medium enterprises.'],
        'related' => ['services' => ['it-amc', 'web-development', 'lead-generation', 'custom-business-applications'], 'solutions' => ['digital-growth', 'it-infrastructure-modernisation'], 'products' => ['lead-management-system']],
    ],
    'enterprises' => [
        'priority' => false,
        'tagline' => 'Integration, automation and infrastructure discipline at scale.',
        'short_description' => 'System integration, workflow applications, infrastructure management and security for larger organisations.',
        'description' => '<p>Larger organisations carry many systems and many teams. Markedge supports them with integration and automation between systems, workflow applications for specific departments, and infrastructure and security operations run to documented standards.</p>',
        'challenges' => [['title' => 'System sprawl', 'text' => 'Integrations and automation between established systems.'], ['title' => 'Standards', 'text' => 'Infrastructure, security and documentation to a defined baseline.']],
        'faqs' => [],
        'seo' => ['title' => 'Technology Services for Enterprises | Markedge Technologies', 'description' => 'System integration, workflow applications, infrastructure management and security for larger organisations.'],
        'related' => ['services' => ['api-development', 'custom-business-applications', 'server-infrastructure-management', 'cybersecurity'], 'solutions' => ['business-automation', 'it-infrastructure-modernisation'], 'products' => ['recruitment-management-system']],
    ],
];
