<?php

/**
 * Phase 12 content library — products: purpose, benefits, use cases, FAQs and SEO. Modules,
 * features, capabilities, deployment, security statements and documentation live in
 * product-platform.php (Phase 15 hierarchy).
 */
return [
    'lead-management-system' => [
        'tagline' => 'Capture, track and follow up every enquiry in one place.',
        'short_description' => 'Markedge\'s lead management software for businesses that want every enquiry recorded with its source, assigned to an owner and followed through to an outcome.',
        'long_description' => '<p>Enquiries arrive from websites, calls, referrals and campaigns, and too often live in inboxes and spreadsheets where follow-up depends on memory. The Lead Management System gives sales and marketing teams a single record of every enquiry: where it came from, who owns it, what has happened and what happens next.</p><p>It is built by Markedge for the businesses we work with on lead generation and sales management, and it connects naturally to the website lead capture and attribution we deliver under our Grow services.</p><p>Request a demo to see the current product with your own scenarios. Detailed module and integration information is provided during the demo so that what you evaluate reflects the product as it is today.</p>',
        'benefits' => [
            ['title' => 'One record per enquiry', 'text' => 'Every lead has a source, an owner, a history and a next action.'],
            ['title' => 'Follow-up you can see', 'text' => 'Managers see what is waiting, what is overdue and what converted.'],
            ['title' => 'Source reporting', 'text' => 'Enquiries reported by campaign, channel and page so marketing spend is grounded in results.'],
        ],
        'use_cases' => [
            ['title' => 'Sales teams handling website and campaign enquiries', 'text' => 'Route and follow up leads generated by marketing without losing context.'],
            ['title' => 'Businesses replacing spreadsheet lead tracking', 'text' => 'Move from shared sheets to a structured record with ownership and history.'],
            ['title' => 'Agencies and consultancies managing pipeline', 'text' => 'Track enquiries from first contact to proposal and outcome.'],
        ],
        'faqs' => [
            ['question' => 'Who is the Lead Management System for?', 'answer' => 'Sales and marketing teams that receive enquiries from several sources and need ownership, follow-up and reporting in one place.'],
            ['question' => 'Can we see it before deciding?', 'answer' => 'Yes. Request a demo and we will walk through the product with your scenarios.'],
            ['question' => 'How does it relate to Markedge lead generation services?', 'answer' => 'Website forms and campaigns we build can feed enquiries with their attribution into the system, so source reporting is consistent.'],
        ],
        'seo' => ['title' => 'Lead Management System | Markedge Technologies', 'description' => 'Lead management software from Markedge: record every enquiry with its source, assign an owner, follow up and report by campaign. Request a demo.'],
        'related' => ['solutions' => ['sales-management', 'business-automation'], 'industries' => ['real-estate', 'education', 'professional-services', 'smes'], 'services' => ['lead-generation', 'performance-marketing']],
    ],
    'recruitment-management-system' => [
        'tagline' => 'Run hiring as a process, from requisition to offer.',
        'short_description' => 'Markedge\'s recruitment management software for teams that want vacancies, candidates, interviews and decisions tracked in one structured workflow.',
        'long_description' => '<p>Recruitment involves many people and many steps: approving a vacancy, sourcing candidates, screening, scheduling interviews, collecting feedback and making an offer. When that runs over e-mail and spreadsheets, candidates wait, feedback gets lost and nobody can see where a hire is stuck.</p><p>The Recruitment Management System gives HR teams, hiring managers and recruiters a shared, structured view of every vacancy and candidate, with the history of each step.</p><p>Request a demo to see the current product with your own hiring process. Module, integration and deployment details are provided during the demo so your evaluation reflects the product as it is today.</p>',
        'benefits' => [
            ['title' => 'Every candidate accounted for', 'text' => 'Status, stage and history visible for each applicant and vacancy.'],
            ['title' => 'Coordinated hiring', 'text' => 'HR, hiring managers and recruiters work from the same record.'],
            ['title' => 'Process reporting', 'text' => 'Time in stage, pipeline and outcomes reported per vacancy.'],
        ],
        'use_cases' => [
            ['title' => 'HR teams managing several open vacancies', 'text' => 'Keep candidates moving with visible stages and owners.'],
            ['title' => 'Recruitment agencies', 'text' => 'Track candidates across client vacancies with a consistent process.'],
            ['title' => 'Growing companies formalising hiring', 'text' => 'Replace ad-hoc e-mail hiring with a repeatable workflow.'],
        ],
        'faqs' => [
            ['question' => 'Who is the Recruitment Management System for?', 'answer' => 'HR teams, hiring managers and recruitment agencies that need vacancies and candidates managed in one structured workflow.'],
            ['question' => 'Can it be adapted to our hiring stages?', 'answer' => 'Hiring stages and their configuration are covered in the demo, where we map your current process to the product.'],
            ['question' => 'How do we evaluate it?', 'answer' => 'Request a demo; we walk through the product with your process and answer implementation questions.'],
        ],
        'seo' => ['title' => 'Recruitment Management System | Markedge Technologies', 'description' => 'Recruitment management software from Markedge: vacancies, candidates, interviews and decisions in one structured workflow. Request a demo.'],
        'related' => ['solutions' => ['recruitment-automation', 'business-automation'], 'industries' => ['recruitment', 'professional-services', 'enterprises'], 'services' => ['ai-automation', 'custom-business-applications']],
    ],
];
