<?php

/**
 * Phase 12 content library — BUILD pillar (Technology). Descriptive service copy only: no clients,
 * numbers, certifications, named vendors or outcome claims. Technologies are deliberately not named
 * until the engineering team confirms the supported stack (see MARKEDGE_PHASE_12_IMPLEMENTATION.md §7).
 */
return [
    'software-development' => [
        'tagline' => 'Custom software built around how your business actually works.',
        'short_description' => 'Design, engineering and delivery of business software: from requirements and architecture to release, support and continuous improvement.',
        'overview' => '<p>Off-the-shelf software fits the average business. When your processes, data or customer journey are specific to you, custom software is how you stop working around tools and start working through them.</p><p>Markedge builds software as an engineering engagement, not a one-off project: we define the problem with you, agree an architecture that can grow, deliver in increments you can review, and stay responsible for what we ship.</p><p>Typical starting points are an internal process that lives in spreadsheets and email, a customer-facing portal that needs to connect to existing systems, or an ageing application that has become risky to change.</p>',
        'benefits' => [
            ['title' => 'Fits the process, not the other way round', 'text' => 'Workflows, data models and permissions are designed from your operation, so staff stop maintaining workarounds.'],
            ['title' => 'Built to change', 'text' => 'Clear architecture, tests and documentation mean the software can evolve as the business does, without a rewrite.'],
            ['title' => 'Owned by you', 'text' => 'You own the code, the data and the accounts. There is no lock-in to Markedge to keep the system running.'],
        ],
        'features' => [
            ['title' => 'Requirements and scoping', 'text' => 'Workshops that turn business goals into a prioritised scope with clear acceptance criteria.'],
            ['title' => 'Architecture and data design', 'text' => 'Domain models, integration boundaries and security decisions documented before build starts.'],
            ['title' => 'Incremental delivery', 'text' => 'Working software in short cycles, reviewed with your team, with automated tests protecting each release.'],
            ['title' => 'Release and support', 'text' => 'Controlled deployment, monitoring, a defined support path and a plan for continuous improvement.'],
        ],
        'process' => [
            ['title' => 'Discover', 'text' => 'Understand the business process, users, systems and constraints; identify the smallest release that creates value.'],
            ['title' => 'Define', 'text' => 'Agree scope, architecture, data ownership, security requirements and the delivery plan.'],
            ['title' => 'Build', 'text' => 'Engineer in iterations with automated tests, code review and regular demonstrations.'],
            ['title' => 'Release', 'text' => 'Deploy to production with monitoring, documentation and user onboarding.'],
            ['title' => 'Improve', 'text' => 'Measure usage, gather feedback and plan the next increments.'],
        ],
        'deliverables' => ['Scope and architecture document', 'Working software delivered in reviewed increments', 'Automated test suite and deployment pipeline', 'Technical and user documentation', 'Handover with source code, environments and credentials owned by you'],
        'faqs' => [
            ['question' => 'How do you decide between custom software and an existing product?', 'answer' => 'We start by mapping the process and checking whether an existing product covers it without heavy customisation. Custom software is recommended only where the process is a genuine differentiator or existing tools would need constant workarounds.'],
            ['question' => 'Who owns the source code?', 'answer' => 'You do. Code, repositories, environments and third-party accounts are set up in your name and handed over with documentation.'],
            ['question' => 'What happens after launch?', 'answer' => 'Every engagement ends with a defined support and improvement plan. Ongoing maintenance can be handled through an IT AMC or a dedicated support arrangement.'],
        ],
        'seo' => ['title' => 'Software Development Services | Markedge Technologies', 'description' => 'Custom business software designed, engineered and supported by Markedge: requirements, architecture, incremental delivery, testing and release. Discuss your requirement.'],
        'related' => ['solutions' => ['custom-software', 'business-automation'], 'industries' => ['smes', 'enterprises', 'startups'], 'products' => []],
    ],
    'web-development' => [
        'tagline' => 'Websites and web applications engineered for performance, security and search.',
        'short_description' => 'Corporate websites, portals and web applications built on a maintainable stack with performance, accessibility and SEO handled from the start.',
        'overview' => '<p>A website is the one system every customer, partner and candidate uses. It has to load fast, be findable, accessible on any device, and easy for your team to update without a developer.</p><p>Markedge builds websites and web applications with the same engineering discipline as any other software: a content model your team owns, a design system that keeps pages consistent, structured data and technical SEO built into the templates, and a deployment process that keeps the site secure.</p><p>Web applications extend this to logged-in experiences: customer portals, dashboards, booking and ordering flows, and tools that connect to your internal systems.</p>',
        'benefits' => [
            ['title' => 'Editable by your team', 'text' => 'Content, navigation, forms and calls to action are managed in a CMS with review and publishing controls, not in code.'],
            ['title' => 'Technically sound from day one', 'text' => 'Performance budgets, responsive images, accessibility and structured data are part of the build, not an afterthought.'],
            ['title' => 'Measured', 'text' => 'Enquiries, calls to action and attribution are tracked first-party so you know which pages produce conversations.'],
        ],
        'features' => [
            ['title' => 'Information architecture', 'text' => 'Page hierarchy, navigation and URL structure designed around how visitors search and decide.'],
            ['title' => 'Design system and templates', 'text' => 'Reusable components and typed content blocks that keep every page consistent and on-brand.'],
            ['title' => 'Technical SEO and performance', 'text' => 'Canonical URLs, sitemaps, schema, image optimisation and caching built into the platform.'],
            ['title' => 'Forms and lead capture', 'text' => 'Enquiry, quote and demo forms with consent, spam protection and attribution to the originating page.'],
        ],
        'process' => [
            ['title' => 'Plan', 'text' => 'Audience, goals, content inventory and search intent mapped into a sitemap and page briefs.'],
            ['title' => 'Design', 'text' => 'Design system, page templates and content blocks agreed before implementation.'],
            ['title' => 'Build', 'text' => 'CMS, templates, forms, SEO engine and integrations implemented and tested.'],
            ['title' => 'Launch', 'text' => 'Content migration, redirects, hosting, monitoring and search engine setup.'],
            ['title' => 'Grow', 'text' => 'Content, conversion and performance improvements driven by real data.'],
        ],
        'deliverables' => ['Sitemap, page briefs and content model', 'Design system and responsive templates', 'CMS with editorial workflow', 'Technical SEO: canonicals, sitemap, schema, redirects', 'Lead capture with attribution and consent', 'Hosting, deployment and monitoring setup'],
        'faqs' => [
            ['question' => 'Can we update the website ourselves?', 'answer' => 'Yes. Pages are built from approved content blocks that editors manage in the CMS, with draft, review and publish states, so changes never require a developer.'],
            ['question' => 'Do you handle hosting and maintenance?', 'answer' => 'Hosting, deployment, backups and monitoring are set up as part of the launch and can be maintained under an IT AMC or support arrangement.'],
            ['question' => 'Will the website be optimised for search?', 'answer' => 'Technical SEO is built into the platform. Content and keyword strategy are covered by our SEO and content marketing services.'],
        ],
        'seo' => ['title' => 'Web Development Services | Markedge Technologies', 'description' => 'Corporate websites, portals and web applications with a CMS your team owns, performance and technical SEO built in, and first-party lead tracking.'],
        'related' => ['solutions' => ['digital-growth', 'customer-experience'], 'industries' => ['smes', 'professional-services', 'real-estate'], 'products' => []],
    ],
    'mobile-app-development' => [
        'tagline' => 'Mobile applications that connect field teams, customers and back-office systems.',
        'short_description' => 'Android and iOS applications for customers, staff and field operations, integrated with your existing systems and released through the app stores.',
        'overview' => '<p>Mobile apps make sense when people need to act away from a desk: field staff capturing data, customers tracking an order, sales teams updating a pipeline on the move.</p><p>Markedge scopes mobile applications around the moments that matter on a phone, keeps the business logic in shared services so the app and your back office stay consistent, and handles the release process across both app stores.</p><p>We help you choose between native, cross-platform and mobile web approaches based on the features you need, the devices in use and how often the app will change.</p>',
        'benefits' => [
            ['title' => 'Right approach for the job', 'text' => 'Native, cross-platform or responsive web, chosen on device features, offline needs and maintenance cost rather than preference.'],
            ['title' => 'Connected to your systems', 'text' => 'Secure APIs link the app to existing data, so mobile users and office users see the same truth.'],
            ['title' => 'Store-ready', 'text' => 'Store listings, review requirements, signing and release management handled with you.'],
        ],
        'features' => [
            ['title' => 'Mobile UX design', 'text' => 'Flows designed for small screens, one-handed use and interrupted sessions.'],
            ['title' => 'Offline and sync', 'text' => 'Data capture that keeps working without connectivity and reconciles safely when back online.'],
            ['title' => 'API layer', 'text' => 'Authenticated, versioned APIs that serve the app and any future channel.'],
            ['title' => 'Release management', 'text' => 'Beta distribution, store submission, crash reporting and update cadence.'],
        ],
        'process' => [
            ['title' => 'Define', 'text' => 'Identify the mobile moments, users and devices; decide the technical approach.'],
            ['title' => 'Design', 'text' => 'Prototype key flows and validate them with real users.'],
            ['title' => 'Build', 'text' => 'Develop app and API in iterations with automated tests and device testing.'],
            ['title' => 'Release', 'text' => 'Store submission, monitoring and support handover.'],
        ],
        'deliverables' => ['Technical approach recommendation', 'Prototype and UI design', 'Published Android and iOS applications', 'API documentation', 'Crash reporting and analytics setup (first-party, privacy-respecting)', 'Release and update plan'],
        'faqs' => [
            ['question' => 'Do we need a native app or is a mobile website enough?', 'answer' => 'If users mainly read and submit information, a responsive web application is usually faster to deliver and maintain. Native or cross-platform apps make sense for offline use, device hardware, notifications or frequent daily use.'],
            ['question' => 'Who publishes the app on the stores?', 'answer' => 'The app is published under your developer accounts so you retain ownership; we manage the submission and review process with you.'],
            ['question' => 'How are updates handled?', 'answer' => 'A release plan defines update cadence, testing and rollout; ongoing maintenance can be covered by a support arrangement.'],
        ],
        'seo' => ['title' => 'Mobile App Development Services | Markedge Technologies', 'description' => 'Android and iOS applications for customers and field teams, integrated with your systems and released through the app stores by Markedge.'],
        'related' => ['solutions' => ['customer-experience', 'business-automation'], 'industries' => ['logistics', 'retail', 'healthcare'], 'products' => []],
    ],
    'product-development' => [
        'tagline' => 'From idea to a software product you can sell, support and grow.',
        'short_description' => 'Product strategy, MVP definition, engineering and release for software products, with the architecture and operations a commercial product needs.',
        'overview' => '<p>Building a product is different from building an internal tool. It needs multi-tenant architecture, onboarding, billing, support processes and a roadmap driven by users rather than a single sponsor.</p><p>Markedge works with founders and business owners to define a minimum viable product that can be validated with real users, engineer it on foundations that scale, and set up the release, monitoring and support routines a product business depends on.</p><p>Our own products are built the same way, which keeps the advice practical.</p>',
        'benefits' => [
            ['title' => 'Validate before you over-build', 'text' => 'An MVP scoped around the core job-to-be-done, released early enough to learn from real users.'],
            ['title' => 'Foundations that scale', 'text' => 'Tenant isolation, roles, audit trails and observability designed in, not retrofitted.'],
            ['title' => 'Operable as a business', 'text' => 'Onboarding, support, release management and metrics set up so the product can be run, not just launched.'],
        ],
        'features' => [
            ['title' => 'Product discovery', 'text' => 'Problem framing, user interviews, competitor review and MVP scope.'],
            ['title' => 'Architecture for products', 'text' => 'Multi-tenancy, authentication, permissions, data protection and integration points.'],
            ['title' => 'Engineering and QA', 'text' => 'Iterative build with automated testing and release pipelines.'],
            ['title' => 'Launch operations', 'text' => 'Monitoring, backups, support workflow and usage measurement.'],
        ],
        'process' => [
            ['title' => 'Discover', 'text' => 'Define the user, the problem and what the first release must prove.'],
            ['title' => 'Shape', 'text' => 'Prototype, prioritise and plan the MVP.'],
            ['title' => 'Build', 'text' => 'Engineer the MVP with production-grade foundations.'],
            ['title' => 'Launch and learn', 'text' => 'Release to early users, measure, and plan the roadmap from evidence.'],
        ],
        'deliverables' => ['Product discovery report and MVP scope', 'Prototype', 'Production-ready MVP', 'Operational setup: monitoring, backups, support process', 'Roadmap based on early usage'],
        'faqs' => [
            ['question' => 'Can you help validate the idea before building?', 'answer' => 'Yes. Discovery and prototyping are designed to test assumptions cheaply before engineering starts.'],
            ['question' => 'Will the product be able to scale later?', 'answer' => 'The MVP is built on foundations chosen for growth: tenant isolation, secure authentication, permissions and observability. Features are kept minimal; the foundation is not.'],
            ['question' => 'Do you take equity or build under contract?', 'answer' => 'Engagements are contract-based. Commercial terms are agreed per project.'],
        ],
        'seo' => ['title' => 'Software Product Development | Markedge Technologies', 'description' => 'Product discovery, MVP engineering and launch operations for software products, on foundations built to scale.'],
        'related' => ['solutions' => ['product-development'], 'industries' => ['startups', 'technology'], 'products' => []],
    ],
    'custom-business-applications' => [
        'tagline' => 'Replace spreadsheets, email chains and disconnected tools with one application.',
        'short_description' => 'Internal applications for operations, approvals, records and reporting, built around your workflow and connected to the systems you already use.',
        'overview' => '<p>Most businesses run important processes on spreadsheets, shared inboxes and generic tools that were never designed for the job. The result is duplicated data, unclear ownership and reports that take days to assemble.</p><p>Custom business applications give each process a proper home: structured records, defined roles, approvals, notifications and reports, with integrations to accounting, HR, CRM or operational systems so data is entered once.</p><p>Typical applications include approval workflows, asset and inventory registers, service desks, field reporting, compliance tracking and management dashboards.</p>',
        'benefits' => [
            ['title' => 'One source of truth', 'text' => 'Records live in one place with history, ownership and access control instead of competing spreadsheets.'],
            ['title' => 'Faster processes', 'text' => 'Approvals, reminders and handovers happen in the application instead of over email.'],
            ['title' => 'Reporting on demand', 'text' => 'Management views built on live data rather than month-end reconstruction.'],
        ],
        'features' => [
            ['title' => 'Workflow and approvals', 'text' => 'Multi-step processes with roles, delegation, audit trail and notifications.'],
            ['title' => 'Records and documents', 'text' => 'Structured data with attachments, versioning and retention rules.'],
            ['title' => 'Integrations', 'text' => 'Connections to finance, HR, CRM, e-mail and messaging systems.'],
            ['title' => 'Dashboards and exports', 'text' => 'Role-based views, scheduled reports and exports for auditors and management.'],
        ],
        'process' => [
            ['title' => 'Map the process', 'text' => 'Document the current process, its exceptions and the data it depends on.'],
            ['title' => 'Design the application', 'text' => 'Data model, roles, screens and integrations agreed with the people who will use it.'],
            ['title' => 'Build and pilot', 'text' => 'Deliver in increments and pilot with one team before wider rollout.'],
            ['title' => 'Roll out', 'text' => 'Migrate data, train users and retire the old spreadsheets.'],
        ],
        'deliverables' => ['Process map and application design', 'Working application with roles and workflow', 'Data migration from existing spreadsheets or systems', 'Integrations and reports', 'Training material and support handover'],
        'faqs' => [
            ['question' => 'Can the application connect to our accounting or HR software?', 'answer' => 'Integration is scoped per system. Where the system offers an API or export, data can be synchronised; where it does not, we design the least manual handover possible.'],
            ['question' => 'How do we migrate data from spreadsheets?', 'answer' => 'Migration is a defined step: we clean and map the existing data with you, import it, and validate it before the old files are retired.'],
            ['question' => 'Who can change the workflow later?', 'answer' => 'Configurable elements such as roles, approval steps and reference lists are managed by your administrators; structural changes are handled through support.'],
        ],
        'seo' => ['title' => 'Custom Business Application Development | Markedge Technologies', 'description' => 'Internal applications for workflows, approvals, records and reporting, built around your process and integrated with the systems you already use.'],
        'related' => ['solutions' => ['business-automation', 'custom-software'], 'industries' => ['manufacturing', 'professional-services', 'enterprises'], 'products' => []],
    ],
    'api-development' => [
        'tagline' => 'Connect the systems your business already depends on.',
        'short_description' => 'API design, integration and middleware that let CRM, ERP, e-commerce, HR and operational systems exchange data reliably.',
        'overview' => '<p>Businesses rarely have a data problem; they have a data movement problem. Orders live in one system, customers in another, invoices in a third, and people re-key information between them.</p><p>Markedge designs and builds the integration layer: APIs that expose your data safely, connectors that synchronise systems, and middleware that handles retries, mapping and monitoring so integrations keep working when something on either side changes.</p><p>We also build public and partner APIs for businesses that need customers or partners to connect to their platform.</p>',
        'benefits' => [
            ['title' => 'Enter data once', 'text' => 'Records flow between systems automatically, removing re-keying and reconciliation.'],
            ['title' => 'Resilient by design', 'text' => 'Retries, idempotency, monitoring and alerting mean failures are visible and recoverable, not silent.'],
            ['title' => 'Future-proof', 'text' => 'Versioned, documented APIs let you replace a system without rewriting every integration.'],
        ],
        'features' => [
            ['title' => 'API design', 'text' => 'REST and event-based APIs with authentication, versioning and documentation.'],
            ['title' => 'System integration', 'text' => 'Connectors between CRM, ERP, accounting, e-commerce, HR and messaging platforms.'],
            ['title' => 'Middleware and queues', 'text' => 'Reliable message handling, transformation, scheduling and error queues.'],
            ['title' => 'Monitoring', 'text' => 'Dashboards and alerts for volumes, failures and latency.'],
        ],
        'process' => [
            ['title' => 'Map the data flows', 'text' => 'Which systems own which data, in which direction it moves and how conflicts are resolved.'],
            ['title' => 'Design contracts', 'text' => 'API specifications, mappings, authentication and failure handling agreed up front.'],
            ['title' => 'Build and test', 'text' => 'Implement with contract tests and sandbox environments on both sides.'],
            ['title' => 'Operate', 'text' => 'Deploy with monitoring, runbooks and a support path.'],
        ],
        'deliverables' => ['Integration architecture and data-flow map', 'API specification and documentation', 'Working integrations with monitoring and alerting', 'Runbook for failures and re-processing', 'Handover and support plan'],
        'faqs' => [
            ['question' => 'What if one of our systems has no API?', 'answer' => 'We assess the available options such as exports, database access or file exchange and design the most reliable path, being clear about any limitations.'],
            ['question' => 'How are integration failures handled?', 'answer' => 'Every integration is built with retries, dead-letter handling and alerts, plus a runbook that explains how to re-process failed records.'],
            ['question' => 'Can you build an API for our partners or customers?', 'answer' => 'Yes. Public and partner APIs include authentication, rate limiting, versioning and documentation.'],
        ],
        'seo' => ['title' => 'API Development & System Integration | Markedge Technologies', 'description' => 'API design, system integration and middleware that connect CRM, ERP, e-commerce and operational systems reliably, with monitoring and documentation.'],
        'related' => ['solutions' => ['business-automation', 'custom-software'], 'industries' => ['retail', 'logistics', 'enterprises'], 'products' => ['lead-management-system']],
    ],
    'ai-automation' => [
        'tagline' => 'Automate repetitive work with rules first and machine learning where it earns its place.',
        'short_description' => 'Workflow automation, document processing and assisted decision-making designed around measurable business tasks rather than technology for its own sake.',
        'overview' => '<p>Automation pays off when a task is frequent, well understood and expensive in people time. Most of that work can be automated with clear rules and integrations; some of it benefits from machine learning, such as classifying documents, extracting data from forms, or routing requests.</p><p>Markedge starts with the task, not the model. We map the process, automate the deterministic parts, and apply AI components only where they are accurate enough to trust and where a human remains in control of the outcome.</p><p>Every automation is measured against the manual baseline it replaces, and every AI-assisted step keeps a review path.</p>',
        'benefits' => [
            ['title' => 'Practical scope', 'text' => 'Candidates are chosen by frequency, cost and error rate, so automation targets the work that matters.'],
            ['title' => 'Human in control', 'text' => 'AI-assisted steps propose; people approve where the decision has business or legal weight.'],
            ['title' => 'Measured', 'text' => 'Time saved, error rates and exceptions are tracked so the value is visible.'],
        ],
        'features' => [
            ['title' => 'Process automation', 'text' => 'Rule-based workflows, scheduled jobs and integrations that remove manual handovers.'],
            ['title' => 'Document and data extraction', 'text' => 'Capture of structured data from invoices, forms, e-mails and reports with validation.'],
            ['title' => 'Classification and routing', 'text' => 'Automatic categorisation of enquiries, tickets and records to the right queue.'],
            ['title' => 'Assisted drafting and search', 'text' => 'Internal assistants over your own documents and data, with access control and audit.'],
        ],
        'process' => [
            ['title' => 'Identify', 'text' => 'Inventory repetitive tasks and quantify the manual effort and error cost.'],
            ['title' => 'Prototype', 'text' => 'Prove accuracy on your real data before committing to a build.'],
            ['title' => 'Implement', 'text' => 'Build the automation with review steps, logging and exception handling.'],
            ['title' => 'Measure and extend', 'text' => 'Compare against the baseline and extend to the next task.'],
        ],
        'deliverables' => ['Automation opportunity assessment', 'Prototype with accuracy results on your data', 'Production automation with review and exception handling', 'Measurement dashboard', 'Governance notes: data use, access and review responsibilities'],
        'faqs' => [
            ['question' => 'Do we need AI, or just automation?', 'answer' => 'Often just automation. Rule-based workflows and integrations solve most repetitive work; AI components are added only where the task requires interpretation and accuracy can be validated.'],
            ['question' => 'How is our data protected?', 'answer' => 'Data handling, storage location and access are agreed at the start, and AI components are chosen and configured to respect those constraints.'],
            ['question' => 'What if the automation makes a mistake?', 'answer' => 'Automations log every action, route exceptions to people and keep a review path for decisions with business impact.'],
        ],
        'seo' => ['title' => 'AI & Automation Services for Business | Markedge Technologies', 'description' => 'Workflow automation, document processing and assisted decision-making scoped around measurable tasks, with people in control and results tracked.'],
        'related' => ['solutions' => ['business-automation', 'recruitment-automation', 'sales-management'], 'industries' => ['professional-services', 'recruitment', 'bfsi'], 'products' => ['lead-management-system', 'recruitment-management-system']],
    ],
    'ui-ux-design' => [
        'tagline' => 'Interfaces people understand the first time.',
        'short_description' => 'User research, interface design and design systems for web and mobile products, internal tools and customer portals.',
        'overview' => '<p>Software succeeds when people can use it without training and without friction. Design is where that is decided: how information is organised, how tasks flow, and how the interface behaves on every screen.</p><p>Markedge designs interfaces from research with real users, prototypes them before development, and delivers design systems that keep products consistent as they grow. Accessibility is part of the definition of done, not a later fix.</p>',
        'benefits' => [
            ['title' => 'Less training, fewer errors', 'text' => 'Task flows designed around how people actually work reduce support load and mistakes.'],
            ['title' => 'Consistency at scale', 'text' => 'A design system gives every new screen the same components, language and behaviour.'],
            ['title' => 'Accessible by default', 'text' => 'Keyboard navigation, contrast, labels and error handling designed in from the start.'],
        ],
        'features' => [
            ['title' => 'User research', 'text' => 'Interviews, task analysis and usability testing with the people who will use the product.'],
            ['title' => 'Information architecture', 'text' => 'Navigation, content structure and terminology that match users\' mental models.'],
            ['title' => 'Interface design and prototyping', 'text' => 'Wireframes to high-fidelity, interactive prototypes tested before build.'],
            ['title' => 'Design systems', 'text' => 'Tokens, components and documentation shared between design and engineering.'],
        ],
        'process' => [
            ['title' => 'Research', 'text' => 'Understand users, tasks and context.'],
            ['title' => 'Structure', 'text' => 'Define flows, navigation and content.'],
            ['title' => 'Design and test', 'text' => 'Prototype, test with users, refine.'],
            ['title' => 'Systemise', 'text' => 'Deliver components and guidelines engineering can implement.'],
        ],
        'deliverables' => ['Research findings and personas grounded in interviews', 'Information architecture and user flows', 'Interactive prototype', 'Design system with components and guidelines', 'Accessibility checklist'],
        'faqs' => [
            ['question' => 'Do you design for existing products as well as new ones?', 'answer' => 'Yes. Redesigns start with an audit of the current interface and usage patterns so improvements target real problems.'],
            ['question' => 'How do you validate a design?', 'answer' => 'Prototypes are tested with representative users on real tasks before development begins.'],
            ['question' => 'Do you deliver a design system?', 'answer' => 'For products that will keep growing, yes: tokens, components and usage guidelines shared with engineering.'],
        ],
        'seo' => ['title' => 'UI/UX Design Services | Markedge Technologies', 'description' => 'User research, interface design, prototyping and design systems for web and mobile products, with accessibility built in.'],
        'related' => ['solutions' => ['customer-experience', 'product-development'], 'industries' => ['startups', 'technology', 'education'], 'products' => []],
    ],
    'cloud-solutions' => [
        'tagline' => 'Applications architected for the cloud, deployed with control.',
        'short_description' => 'Cloud-native application architecture, migration of existing applications, and deployment pipelines with cost, security and reliability designed in.',
        'overview' => '<p>Moving an application to the cloud is not the same as designing it for the cloud. The difference shows up in cost, resilience and how easily the system can change.</p><p>Markedge designs application architectures that use managed services deliberately, migrates existing applications with a plan for data, downtime and rollback, and sets up deployment pipelines so releases are repeatable and reversible.</p><p>For running the underlying infrastructure day to day, see our Cloud Infrastructure service under Operate.</p>',
        'benefits' => [
            ['title' => 'Cost you can predict', 'text' => 'Architecture and sizing decisions made with cost models, not defaults.'],
            ['title' => 'Resilient by design', 'text' => 'Backups, redundancy and recovery objectives defined before go-live.'],
            ['title' => 'Repeatable releases', 'text' => 'Infrastructure as code and pipelines make environments consistent and deployments safe.'],
        ],
        'features' => [
            ['title' => 'Cloud architecture', 'text' => 'Service selection, networking, identity and data design for new applications.'],
            ['title' => 'Application migration', 'text' => 'Assessment, migration plan, data transfer, cut-over and rollback.'],
            ['title' => 'CI/CD and environments', 'text' => 'Pipelines, staging environments and release gates.'],
            ['title' => 'Security and cost controls', 'text' => 'Least-privilege access, secrets management, budgets and alerts.'],
        ],
        'process' => [
            ['title' => 'Assess', 'text' => 'Current architecture, dependencies, data and constraints.'],
            ['title' => 'Design', 'text' => 'Target architecture with cost, security and recovery objectives.'],
            ['title' => 'Migrate or build', 'text' => 'Implement with infrastructure as code and staged cut-over.'],
            ['title' => 'Operate', 'text' => 'Monitoring, backups and handover to your team or our Operate services.'],
        ],
        'deliverables' => ['Assessment and target architecture', 'Migration plan with cut-over and rollback', 'Infrastructure as code and deployment pipelines', 'Security baseline and cost controls', 'Operations handover'],
        'faqs' => [
            ['question' => 'Which cloud provider do you recommend?', 'answer' => 'The recommendation depends on your existing tools, data residency needs, team skills and cost model; we assess before recommending rather than defaulting to one provider.'],
            ['question' => 'Will migration cause downtime?', 'answer' => 'Migration plans define the acceptable downtime window and include rehearsal and rollback steps; many migrations can be staged to minimise interruption.'],
            ['question' => 'Who manages the cloud after migration?', 'answer' => 'Either your team, with documentation and training, or Markedge through the Cloud Infrastructure service under Operate.'],
        ],
        'seo' => ['title' => 'Cloud Application Development & Migration | Markedge Technologies', 'description' => 'Cloud-native architecture, application migration and deployment pipelines with cost, security and recovery objectives designed in.'],
        'related' => ['solutions' => ['it-infrastructure-modernisation', 'custom-software'], 'industries' => ['enterprises', 'technology', 'bfsi'], 'products' => []],
    ],
];
