<?php

/** Phase 12 content library — solutions: business problems mapped to Markedge capabilities. */
return [
    'business-automation' => [
        'tagline' => 'Remove the manual steps between your systems and your people.',
        'short_description' => 'Automate approvals, data handling and hand-offs across the tools you already use, with people kept in control of decisions.',
        'problem_statement' => '<p>Growing businesses accumulate manual work: re-keying data between systems, chasing approvals over e-mail, assembling reports by hand. It is slow, error-prone and invisible until something goes wrong.</p>',
        'approach' => '<p>We map the processes with the highest manual cost, automate the deterministic parts with integrations and workflow applications, apply AI-assisted steps only where they are accurate enough to trust, and measure the result against the manual baseline.</p>',
        'outcomes' => [['label' => 'Data entered once', 'text' => 'Integrations move records between systems automatically.'], ['label' => 'Visible approvals', 'text' => 'Requests, approvals and exceptions tracked in one place.'], ['label' => 'Measured effort saved', 'text' => 'Each automation reported against the work it replaced.']],
        'seo' => ['title' => 'Business Automation Solutions | Markedge Technologies', 'description' => 'Automate approvals, data handling and hand-offs across your existing systems with integrations, workflow applications and measured AI-assisted steps.'],
        'related' => ['services' => ['ai-automation', 'custom-business-applications', 'api-development'], 'industries' => ['professional-services', 'manufacturing', 'smes'], 'products' => ['lead-management-system', 'recruitment-management-system']],
    ],
    'sales-management' => [
        'tagline' => 'Every enquiry captured, owned and followed up.',
        'short_description' => 'A connected path from website and campaign enquiry to sales follow-up and reporting.',
        'problem_statement' => '<p>Enquiries arrive from many channels and get lost between inboxes, spreadsheets and phones. Marketing cannot see which campaigns produce real opportunities, and sales cannot see what is waiting.</p>',
        'approach' => '<p>We build lead capture with attribution into the website and campaigns, route enquiries to owners, and manage follow-up and reporting through the Lead Management System or your existing CRM.</p>',
        'outcomes' => [['label' => 'Attributed enquiries', 'text' => 'Every lead carries its source and landing page.'], ['label' => 'Owned follow-up', 'text' => 'Leads assigned with history and next actions.'], ['label' => 'Source reporting', 'text' => 'Enquiries reported by campaign, channel and page.']],
        'seo' => ['title' => 'Sales & Lead Management Solutions | Markedge Technologies', 'description' => 'Connect website and campaign enquiries to sales follow-up and reporting with lead capture, attribution and the Markedge Lead Management System.'],
        'related' => ['services' => ['lead-generation', 'performance-marketing', 'web-development'], 'industries' => ['real-estate', 'education', 'smes'], 'products' => ['lead-management-system']],
    ],
    'recruitment-automation' => [
        'tagline' => 'Hiring as a structured, visible workflow.',
        'short_description' => 'Vacancies, candidates, interviews and decisions managed in one process instead of e-mail threads.',
        'problem_statement' => '<p>Hiring involves many people and steps. Without a shared system, candidates wait for feedback, interviewers lose context and managers cannot see where a hire is stuck.</p>',
        'approach' => '<p>We implement the Recruitment Management System around your hiring stages, integrate it with the tools your team uses where practical, and automate reminders, scheduling and status updates.</p>',
        'outcomes' => [['label' => 'One candidate record', 'text' => 'Stage, feedback and history for every applicant.'], ['label' => 'Coordinated interviews', 'text' => 'Scheduling and feedback captured in the workflow.'], ['label' => 'Pipeline visibility', 'text' => 'Time in stage and outcomes per vacancy.']],
        'seo' => ['title' => 'Recruitment Automation Solutions | Markedge Technologies', 'description' => 'Manage vacancies, candidates, interviews and decisions in one structured workflow with the Markedge Recruitment Management System.'],
        'related' => ['services' => ['ai-automation', 'custom-business-applications'], 'industries' => ['recruitment', 'enterprises', 'professional-services'], 'products' => ['recruitment-management-system']],
    ],
    'digital-growth' => [
        'tagline' => 'From being found to being contacted.',
        'short_description' => 'Search visibility, content, campaigns and conversion connected into one measured acquisition path.',
        'problem_statement' => '<p>Many businesses have a website, some content and occasional campaigns, but no connected path from search to enquiry and no reliable way to know what works.</p>',
        'approach' => '<p>We research demand, fix the technical foundation, build intent-matched content and landing pages, add paid channels where they add demand, and attribute every enquiry to its source.</p>',
        'outcomes' => [['label' => 'Intent-matched pages', 'text' => 'Commercial and informational content organised by what customers search for.'], ['label' => 'Connected channels', 'text' => 'Search, content, social and paid media aimed at the same pages.'], ['label' => 'Attributed enquiries', 'text' => 'First-party tracking from campaign to lead.']],
        'seo' => ['title' => 'Digital Growth Solutions | Markedge Technologies', 'description' => 'Search visibility, content, campaigns and conversion connected into one measured acquisition path from search to enquiry.'],
        'related' => ['services' => ['seo', 'content-marketing', 'performance-marketing', 'conversion-optimisation'], 'industries' => ['smes', 'real-estate', 'education', 'professional-services'], 'products' => ['lead-management-system']],
    ],
    'it-infrastructure-modernisation' => [
        'tagline' => 'Move from ageing, unmanaged IT to a maintained, secure and recoverable environment.',
        'short_description' => 'Assessment, remediation and ongoing operation of networks, servers, cloud, security and backups.',
        'problem_statement' => '<p>IT that grew without a plan carries hidden risk: unpatched servers, undocumented networks, backups nobody has tested, and security that depends on luck.</p>',
        'approach' => '<p>We assess the environment, fix the highest risks first, standardise configuration and documentation, and operate it under an agreement with defined scope, monitoring and reporting.</p>',
        'outcomes' => [['label' => 'Known environment', 'text' => 'Inventory, documentation and monitoring in place.'], ['label' => 'Reduced risk', 'text' => 'Patching, access control and tested backups.'], ['label' => 'Defined operations', 'text' => 'Scope, priorities and reporting agreed in writing.']],
        'seo' => ['title' => 'IT Infrastructure Modernisation Solutions | Markedge Technologies', 'description' => 'Assess, remediate and operate networks, servers, cloud, security and backups under an agreement with defined scope and reporting.'],
        'related' => ['services' => ['it-amc', 'cybersecurity', 'backup-disaster-recovery', 'server-infrastructure-management', 'cloud'], 'industries' => ['manufacturing', 'healthcare', 'bfsi', 'smes'], 'products' => []],
    ],
    'custom-software' => [
        'tagline' => 'Software that fits the process instead of forcing the process to fit software.',
        'short_description' => 'Custom applications, integrations and cloud foundations for processes generic tools cannot handle.',
        'problem_statement' => '<p>Off-the-shelf tools cover the average case. When your process is a differentiator, or your data does not fit, teams end up working around software instead of through it.</p>',
        'approach' => '<p>We define the smallest valuable release, design an architecture that can grow, build in reviewed increments with tests, and hand over code and environments you own.</p>',
        'outcomes' => [['label' => 'Process fit', 'text' => 'Workflows and data models designed from your operation.'], ['label' => 'Maintainable', 'text' => 'Tests, documentation and clear architecture.'], ['label' => 'Owned', 'text' => 'Code, environments and accounts in your name.']],
        'seo' => ['title' => 'Custom Software Solutions | Markedge Technologies', 'description' => 'Custom applications, integrations and cloud foundations for business processes that generic tools cannot handle, delivered as an accountable engineering engagement.'],
        'related' => ['services' => ['software-development', 'custom-business-applications', 'api-development', 'cloud-solutions'], 'industries' => ['enterprises', 'manufacturing', 'logistics'], 'products' => []],
    ],
    'product-development' => [
        'tagline' => 'Take a software product from idea to market.',
        'short_description' => 'Discovery, MVP engineering and launch operations for founders and businesses building a product.',
        'problem_statement' => '<p>Product ideas fail on over-building before validation, or on foundations that cannot support paying customers.</p>',
        'approach' => '<p>We scope an MVP around the core job, build it on production-grade foundations, and set up the release, monitoring and support routines a product business needs.</p>',
        'outcomes' => [['label' => 'Validated scope', 'text' => 'An MVP released early enough to learn from users.'], ['label' => 'Scalable foundation', 'text' => 'Tenancy, permissions and observability designed in.'], ['label' => 'Operable product', 'text' => 'Onboarding, support and metrics ready at launch.']],
        'seo' => ['title' => 'Software Product Development Solutions | Markedge Technologies', 'description' => 'Discovery, MVP engineering and launch operations for founders and businesses building a software product.'],
        'related' => ['services' => ['product-development', 'ui-ux-design', 'cloud-solutions'], 'industries' => ['startups', 'technology'], 'products' => []],
    ],
    'customer-experience' => [
        'tagline' => 'Digital touchpoints customers can actually use.',
        'short_description' => 'Websites, portals, apps and interfaces designed and built around how customers want to interact.',
        'problem_statement' => '<p>Customers judge a business by its digital touchpoints: a slow website, a confusing portal or an app that does not work offline costs trust and enquiries.</p>',
        'approach' => '<p>We research how customers interact, design interfaces and flows around real tasks, build them on a performant, accessible platform and measure engagement and conversion.</p>',
        'outcomes' => [['label' => 'Usable interfaces', 'text' => 'Flows designed from user research and tested before build.'], ['label' => 'Fast and accessible', 'text' => 'Performance and accessibility built into the platform.'], ['label' => 'Measured', 'text' => 'Engagement and enquiries tracked first-party.']],
        'seo' => ['title' => 'Customer Experience Solutions | Markedge Technologies', 'description' => 'Websites, portals, apps and interfaces designed and built around how customers want to interact, with performance and accessibility built in.'],
        'related' => ['services' => ['ui-ux-design', 'web-development', 'mobile-app-development', 'conversion-optimisation'], 'industries' => ['retail', 'healthcare', 'education'], 'products' => []],
    ],
];
